### ISSUE TITLE
Modify CONTRIBUTING.md

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#1]
Should probably remove the need for a ICLA. Anything else we need to do?

**Comment by gordonwoodhull** [comment]
I think that's about it. I think we should also start an AUTHORS file and point the copyright notice in the LICENSE to it, i.e. 

```
Copyright 2012-2015 Square, Inc, and crossfilter contributors.
See the AUTHORS file at the top level of this distribution and 
https://github.com/crossfilter/crossfilter/blob/master/AUTHORS
```

**Comment by gordonwoodhull** [comment]
The tome on the subject: http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html
