### ISSUE TITLE
Support unpkg and Observable?

### ISSUE THREAD

**Issue by gordonwoodhull** [crossfilter/crossfilter#106]
@Fil wrote a nice demo of dc.js 3.0 in Observable: https://beta.observablehq.com/@fil/hello-dc-js-v2

He had to use `require('https://bundle.run/dc')` in order to load dc. The same is true of crossfilter2.

I am no expert in the state of the art of JS modules - hoping it will settle down a bit - but it looks like the reason `require('crossfilter2')` doesn't work directly is because our `pkg.main` is `./index.js` and that uses `module`:

```js
module.exports = require("./src/crossfilter").crossfilter;
```
The console shows the error `module is not defined`

Here's a demo

https://beta.observablehq.com/@gordonwoodhull/require-crossfilter2

My guess is that if we define `unpkg` pointing to `crossfilter.js` that will work, but I don't know any way to test this except trying. Does this make sense?

**Comment by Fil** [comment]
My suggestion it to try things out without publishing to npm, which I do (for the modules I'm publishing like d3-geo-polygon), just by using for example:
```
 require("http://localhost/d3/d3-geo-polygon/build/d3-geo-polygon.js")
```

(Amazingly, it works.)

(I don't know much about packaging modules, I just follow what Mike did for the other d3-xxx modules.)

**Comment by gordonwoodhull** [comment]
That's a good point. Yes, the UMD package itself works; I can also do

```js
require('https://unpkg.com/crossfilter2/crossfilter.js')
```

The problems seems to be just that unpkg finds the wrong entry point.

**Comment by Fil** [comment]
Cool. Then it might just be a question of adding 
```
  "unpkg": "crossfilter.min.js",
```
in package.json (see https://github.com/d3/d3-geo-polygon/blob/master/package.json#L28 )

**Comment by gordonwoodhull** [comment]
Welp, I'm gonna try it. I think the worst that could happen is we waste a version number.

Publishing as 1.4.6...

**Comment by gordonwoodhull** [comment]
Yep, that did it! Thanks @Fil!

**Comment by gordonwoodhull** [comment]
@esjewett, I realized I missed a couple of steps - it's now tagged and has GitHub release notes. Please LMK if I missed anything else.

**Comment by esjewett** [comment]
@gordonwoodhull Thank you! And because I am underwater, your release would also have picked up #102, #101, #100, and #98...

**Comment by gordonwoodhull** [comment]
Thanks @esjewett! I've added those to the release notes.
