### ISSUE TITLE
Undocumented feature: dimension creation with field name

### ISSUE THREAD

**Issue by ricardo-reis-1970** [crossfilter/crossfilter#112]
The API Reference, when refering to `crossfilter.dimension(value [, isArray])` only describes `value` as an accessor function. However, the very first lines of crossfilter.dimension are:
```javascript
  function dimension(value, iterable) {

    if (typeof value === 'string') {
      var accessorPath = value;
      value = function(d) { return result(d, accessorPath); }; // line 1319
    }
```
These evaluate  whether `value` is a string, in which case an internal accessor function is ready. Function `result(object, path, defaultValue)` has the longest comment description in the entire library, it's the whole point of module 2 (`"./result"`) and its only call is in line 1319, above.

It's a shame that this feature is not described in the documentation, because it would make some code patterns simpler and more natural. For single property dimensions, instead of something like:
```javascript
var paymentsByTotal = payments.dimension(function(d) { return d.total; }); 
```
we could just say:
```javascript
var paymentsByTotal = payments.dimension("total"); 
```

**Comment by gordonwoodhull** [comment]
It's a path expression language which came from lodash.result/[lodash.get](https://lodash.com/docs/4.17.15#get). It is being replaced with something based on [deepobj](https://github.com/ranfdev/deepobj) in 1.5.

I put a link to #56 in the docs because it's not succinctly described anywhere else.
