### ISSUE TITLE
Types for `dimension()` do not support array dimensions

### ISSUE THREAD

**Issue by beaugunderson** [crossfilter/crossfilter#120]
E.g. in this example, where `d.interventions` is an array of strings, and `true` is passed to tell crossfilter it's an array dimension: 

```js
const interventionDimension = ndx.dimension(d => d.interventions, true);
````

I get this error:

> Type 'string[]' is not assignable to type 'NaturallyOrderedValue'. Type 'string[]' is not assignable to type 'string'.

If I cast `d.interventions as any` I can ignore the error, but would love the type support for arrays. :)

**Comment by esjewett** [comment]
Yup, this is an issue. I think we need to change the signature of `selector` (https://github.com/crossfilter/crossfilter/blob/master/index.d.ts#L87) to accept an `OrderedValueSelector` or another selector function that returns on array.
