### ISSUE TITLE
Type definitions contain a `const enum` which breaks with `--isolatedModules`

### ISSUE THREAD

**Issue by beaugunderson** [crossfilter/crossfilter#121]
I've worked around the issue with `skipLibCheck: true`, but for background see [this issue](https://github.com/Microsoft/TypeScript/issues/20703).

I use typescript with babel, which is the default setup for `create-react-app` when TS is enabled. CRA insists on `--isolatedModules` being turned on, which forbids const enums in `.d.ts` files.

![screenshot](https://i.imgur.com/5Ygz0i0.png)

**Comment by esjewett** [comment]
I think this is addressed by #117, which I just merged. If you need me to cut a release, please let me know. Now on to the other issues you just opened ;)

**Comment by beaugunderson** [comment]
@esjewett thanks so much! would love a release for this but I can pin to master for the time being :)

**Comment by beaugunderson** [comment]
@esjewett I verified that everything does work on master with `skipLibCheck: false` though 👍
