### ISSUE TITLE
Document empty array case for array/tag dimensions

### ISSUE THREAD

**Issue by louMoxy** [crossfilter/crossfilter#128]
Hi, 

Found a bit of bug when filtering on an array dimension, when the data contains an empty array. 

I have made a codepen here: https://codepen.io/louisemoxy/pen/ywxeMv?editors=0012

Version: 1.4.6

Happy to make a PR if you can point me in the right direction. 

Thank you,

**Comment by gordonwoodhull** [comment]
Interesting, I was just looking into another array/tag dimension bug #127, having to do with adding/removing rows while a tag dimension is filtered.

Would you be willing to start with a PR adding a test? You'll find some tag/array dimension tests with the keyword "iterable" in [test/crossfilter-test.js](https://github.com/crossfilter/crossfilter/blob/master/test/crossfilter-test.js). I thought I saw some related test cases but we probably didn't cover that one.

As described in the readme, you can run tests with `npm install; npm test`

**Comment by louMoxy** [comment]
Thanks @gordonwoodhull I have added the tests in a PR https://github.com/crossfilter/crossfilter/pull/129

**Comment by esjewett** [comment]
I've commented on #129 with some suggestions.

**Comment by gordonwoodhull** [comment]
As discussed in #129, it's working as expected given the design, but the design needs to be documented better and this case should be called out.

**Comment by gordonwoodhull** [comment]
[Documented it.](https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_with_arrays)
