### ISSUE TITLE
ComparableObject definition and TypeScript

### ISSUE THREAD

**Issue by vfaure-amadeus** [crossfilter/crossfilter#131]
Hello,

While trying to make use of the possibility to create dimensions with Arrays (of string), I face an issue in TypeScript.
Here is the error :

`error TS2322: Type 'string[]' is not assignable to type 'NaturallyOrderedValue'.
  Type 'string[]' is not assignable to type 'ComparableObject'.
    Types of property 'valueOf' are incompatible.
      Type '() => Object' is not assignable to type '() => string | number | boolean'.
        Type 'Object' is not assignable to type 'string | number | boolean'.
          The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
            Type 'Object' is not assignable to type 'true'.
`

I'm indeed passing an Array of string, which should in fact be a ComparableObject by the definition, since it contains ComparableValue objects.
But the interface definition in index.d.ts is : 

`  export interface ComparableObject {
    valueOf(): ComparableValue;
  }
`

And if you apply valueOf() to an Array, you'll get Object, you'll never get a ComparableValue which is the condition. Or am I doing something wrong ?

This is the way I call dimension : 

`const projectsDimension = this.records.dimension(r => r.projects, true);`

this.records is a crossfilter, r.projects is declared as Array\<string\>.

**Comment by gordonwoodhull** [comment]
Rats, we just did some fixes in this area (#126).

Any chance you'd like to hack on the TypeScript definitions to correct them?

**Comment by vfaure-amadeus** [comment]
I was using 1.4.6 apparently even though I specified anything superior to 1.4.0 and updated 2 days ago.
Issue has indeed been fixed with 1.4.7, closing the ticket if I can, thanks for the reply.

**Comment by gordonwoodhull** [comment]
Awesome, glad to hear it!
