### ISSUE TITLE
crossfilter.groupAll not removing correctly -- depends on number dimensions

### ISSUE THREAD

**Issue by thatcort** [crossfilter/crossfilter#138]
I have a crossfilter with a groupAll counting reducer. I have found that when I use a filterFunction on a dimension, I sometimes end up with a discrepancy between crossfilter.groupAll.value() and the crossfilter.allFiltered() size. 

crossfilter.allFiltered always returns the correct items. The groupAll remove function is not called for a certain set of items in the crossfilter, and it reports too many items.

What's weird is that it only seems to happen when I have 32 dimensions on the crossfilter.

So far I've been unable to create a reproducible testcase. It's very reproducible in my code, but I'm not sure how to export that so someone else can inspect it.

I can keep trying to make a test case, but am hoping someone can suggest places to inspect either my code or the crossfilter code to find the problem.

**Comment by esjewett** [comment]
I’d guess this is happening because one of your dimensions is returning values that are not naturally ordered, causing the group to be missed. You’ll need to share code or a reproducible test case. If it’s a bug with the 32 dimension cutoff, then it should be reproducible.

**Comment by gordonwoodhull** [comment]
Hmm, that sounds plausible but a groupAll doesn't use a dimension so there shouldn't be any ordering issues.

Strongly agree that we need runnable example or test case in order to diagnose this.

**Comment by thatcort** [comment]
I managed to create a test case and it's weirder than I thought. It only occurs with 32 dimensions (so "30 columns" in the test case) and only if I log the groupAll count before applying the filterFunction. The attached test case should run in the projects test folder.

[groupAll-test.js.txt](https://github.com/crossfilter/crossfilter/files/3291842/groupAll-test.js.txt)

**Comment by gordonwoodhull** [comment]
This is very weird. Thanks for the test case @thatcort!

Calling `.value()` causes the value to be computed, and it also clears an internal bit `resetNeeded`, which allows incremental computation. So it's a completely different mechanism and code path that calculates the value if the value has been read before filtering happens... that much makes sense.

Where exactly the bug is, I didn't find. Probably 4:30pm on a Friday is not the best time to look at this!

**Comment by esjewett** [comment]
I hope I can look at it this weekend. One interesting question is whether this happens in old crossfilter (or 1.3, I guess) before the support for numbers of dimensions >32.

**Comment by thatcort** [comment]
Any thoughts on when this might be fixed?

I'd like to be more help, but am finding all the bit manipulation in the code pretty opaque to debug.

**Comment by thatcort** [comment]
I did a bit more investigation. The bug occurs every 32nd dimension (so 32, 64, 96...) and is not limited to filterFunction (also occurs for filterRange). This updated test case will test dimensions up to 300.
[groupAll2-test.js.txt](https://github.com/crossfilter/crossfilter/files/3368917/groupAll2-test.js.txt)

**Comment by TijmenW** [comment]
I also did some research, but still cant pinpoint where the paths diverge.

**Comment by TijmenW** [comment]
I also did some research, but still cant pinpoint where the paths diverge. 

I did verify however that calling the private reset method solves it, and that it's independent of the number of rows.

**Comment by TijmenW** [comment]
I think I found something.

There is a overflow somewhere in the bitarray stuff.

**Comment by gordonwoodhull** [comment]
Interesting! Thanks for investigating, @TijmenW!

JavaScript bitwise operators do [treat their operands as a sequence of 32 bits](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators), and what's more, as *signed* 32-bit integers, so that 32nd bit could cause problems. I have not looked closely at the code, though.

**Comment by TijmenW** [comment]
That was indeed the problem. 

I solved it, will send a pull request after clean some stuff up.

**Comment by TijmenW** [comment]
Anyway, feel free to merge.
