### ISSUE TITLE
Incorrect result in group and reduceSum

### ISSUE THREAD

**Issue by bhargavbd** [crossfilter/crossfilter#153]
I am having a peculiar issue where the group and reduceSum function ends up returning results which should not appear.

Below is the sample data and code
`let raw=[{"investOperate":"Invest","code":"40985785","cost":154.7},{"investOperate":"Invest","code":"40986425","cost":1156},{"investOperate":"Invest","code":"40986425","cost":10873},{"investOperate":"Invest","code":"40985785","cost":31504},{"investOperate":"Invest","code":"40986425","cost":1179},{"investOperate":"Invest","code":"40985785","cost":4071},{"investOperate":"Operate","code":"40792175","cost":1694},{"investOperate":"Operate","code":"40792175","cost":462},{"investOperate":"Invest","code":"40986070","cost":1005.16},{"investOperate":"Invest","code":"41020365","cost":29304}];`

```
let data=crossfilter(raw);
let codeDim = data.dimension(d => d.code);
let investOperateDim = data.dimension(d => d.investOperate);
investOperateDim.filter('Operate');
```

I am first applying a filter on investOperateDim and then grouping dimension "codeDim" and use the reduceSum function, I get 5 objects and should return just one. The code I used is this :
`codeDim.group().reduceSum(d=>d.cost).all();`

If I use either of the below codes, I get the correct set of `array.` though not grouped but indicating that filter has been applied.
`codeDim.top(10)`
or 
`data.allFiltered()`

I am very new to this platform. Apologies if I am missing anything apparent above or my issue is not correctly structured. Any help is appreciated.

**Comment by gordonwoodhull** [comment]
Crossfilter returns zeroes for empty bins.

https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#bins-of-value-zero-are-still-included

**Comment by bhargavbd** [comment]
Thank you !!
