### ISSUE TITLE
Reduce merges "0" and "null" together

### ISSUE THREAD

**Issue by alxnddr** [crossfilter/crossfilter#164]
When a dimension contains both 0 and null reduced values for these are merged.
 
```
const data = [
  { a: 0, b: 1 },
  { a: 1, b: 2 },
  { a: null, b: 10 },
];

const dataset = crossfilter(data);
const dimension = dataset.dimension((item) => item.a);
const items = dimension.group().reduceSum((item) => item.b);
console.log(items.all())
```

Actual:
```
[ { key: 0, value: 11 }, { key: 1, value: 2 } ]
```

Expected:
```
[ { key: 0, value: 1 }, { key: 1, value: 2 }, { key: null, value: 10 } ]
```

**Comment by esjewett** [comment]
Crossfilter dimension functions must return well-ordered values. There is a discussion of this requirement here: https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#natural-ordering-of-dimension-and-group-values

When these functions return non-well-ordered values, you do see the types of issues you are describing.

**Comment by gordonwoodhull** [comment]
This behaves as specified, and I don’t think there is any way for crossfilter to deal with `NaN` or `null` consistently given its design.

However, other languages have NA values and they are clearly useful.

The best workaround I have found is to use a valid number that is clearly outside the domain, like `-10000` or `-Infinity`. It requires some annoying special cases but it behaves consistently.
