### ISSUE TITLE
Return existing dimensions and groups through an API

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#18]
crossfilter.dimensions()
dimension.groups()

**Comment by gordonwoodhull** [comment]
Doesn't this beg the question of what to do with the dimensions and groups once you've fetched them? 

Dimensions and groups don't have any getters, either.

**Comment by esjewett** [comment]
Yes, that's right. A getter for the accessor that was passed to the dimension or group on creation would probably be a good addition.

But for my immediate purposes I mostly am thinking about garbage collection. I tend to work on apps that create and remove dimensions and groups dynamically based on user actions, and with Palladio right now we are starting to work on better support for 3rd-party/contrib components. Components in Palladio are responsible for managing their own lifecycle, but it would be nice if we could make an attempt to clean up after 3rd-party components that don't do this correctly.

We can probably manage this by taking away direct access to the Crossfilter in Palladio and giving wrapper functions for creating dimensions, allowing us to register every dimension created. That would be an alternative approach.

**Comment by esjewett** [comment]
So, should we close this? Seems like this kind of functionality is going to live in http://github.com/crossfilter/universe

**Comment by tannerlinsley** [comment]
Yeah, we should put that in Universe.
