### ISSUE TITLE
Merge array extension fix from square/crossfilter

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#19]
https://github.com/square/crossfilter/commit/0be70ae431c71e68c7385a0dc913f1d2100b199b

**Comment by gordonwoodhull** [comment]
Done in bb606ce1749912f000e4d9fc936732e596aec343

**Comment by esjewett** [comment]
Thanks - that was quick!

FYI - @tannerlinsley I think this has a small impact on the 32+ dimension stuff. We may want to merge it into that branch.
