### ISSUE TITLE
Wiki and documentation

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#2]
Unclear if we can or should transfer at least the API documentation from the original repository. Thoughts?

My assumption is that the documentation is offered under the same license as the rest of the code, so it would be OK to copy it over.

**Comment by derekperkins** [comment]
It should be, though I'm no expert. I just asked on the original thread over there if they have any concerns blessing our fork. Assuming no issues there, I don't think we need to worry.

**Comment by esjewett** [comment]
Github's a bit over-aggressive about closing referenced issues sometimes ;-)

**Comment by gordonwoodhull** [comment]
haha, "does not fix ..."!

**Comment by gordonwoodhull** [comment]
@esjewett, looks like you already forked the wiki. 

I updated the home page with the same stuff from CONTRIBUTING.md, touched gh-pages and made a dummy commit in order to launch crossfilter.github.io

**Comment by esjewett** [comment]
@gordonwoodhull Looks like it came across, indeed. Was it just not turned on, or did I completely miss it? In any case, all is well! I will close this and we can begin on the harder work of actually bringing the codebase up to speed.
