### ISSUE TITLE
Support web workers in crossfilter

### ISSUE THREAD

**Issue by alan-unravel** [crossfilter/crossfilter#22]
As mentioned [here](https://github.com/square/crossfilter/issues/116)

**Comment by esjewett** [comment]
Thanks for creating the issue. I've done some research on this and I'm not optimistic about being able to use Transferrable to move internal Crossfilter calculation to a Web Worker, and the serialization/message-passing approach is too slow for the most part. If you or anyone else has something in mind for the internals of Crossfilter that you think might be able to be pushed out to a Web Worker (even just for parallelization), I'm all ears!

That said, I think there is something to be said for a wrapper that just moves Crossfilter itself entirely to a Web Worker. I built such a wrapper for lcadata.info (https://github.com/esjewett/lcadata/blob/master/src/main/webapp/js/cf-facade.js) and will eventually publish the wrapper as its own project.

**Comment by alan-unravel** [comment]
That would be great, I think crossfilter could benefit from such an extrapolation going forward as it can be quite cumbersome and blocks UI frequently when filtering large datasets.  I will definitely look into it when time allows, perhaps tag this as 'discussion' so people will discuss. Thanks.

**Comment by tannerlinsley** [comment]
I've been thinking about this, looking at @esjewett's LCA implementation.   I agree that it is highly unlikely that crossfilter could have a foot on both sides, but putting it all into a worker and communicating with it via a transparent parallel api is really cool.  

The hope I have is that this parallel api could be made in such a way that it's enclosed in a drop-in plugin, doesn't require any files to be in a specific location (eg. the terrible limitations of `new Worker("worker.js");` and `worker.importScripts`).  Trying to use workers in a build system like gulp or browserify is the worst!

**Comment by esjewett** [comment]
This is being addressed in crossfilter/crossfilter-async. Closing for now. Please continue discussion over there. Development of a Crossfilter-compatible wrapper is a bit stalled out right now :-/
