### ISSUE TITLE
Create AUTHORS file

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#3]
Per @gordonwoodhull comment in #1:

"we should also start an AUTHORS file and point the copyright notice in the LICENSE to it, i.e.

Copyright 2012-2015 Square, Inc, and crossfilter contributors.
See the AUTHORS file at the top level of this distribution and 
https://github.com/crossfilter/crossfilter/blob/master/AUTHORS"

**Comment by esjewett** [comment]
Created file - need to add author names as they contribute.

**Comment by esjewett** [comment]
We need to update the AUTHORS file. Would the following people please let me know how you would like to be listed, or send a pull request?

@MarkHerhold 
@nreese 
@drarmstr 
@tannerlinsley 
@gordonwoodhull 

If I've missed anyone else, please feel free to speak up.

**Comment by esjewett** [comment]
Whoops - also forgot:

@sciyoshi - let me know how you'd like to be listed (name and email address for the 32+ dimension work).

And @nordfjord, did you have a contribution that somehow escaped the commit log, or was that on Reductio?

**Comment by esjewett** [comment]
And we should likely list the authors who contributed under Square if they like:

@jasondavies 
@RandomEtc 
@mbostock 

Thoughts/requests on this from anyone?

**Comment by nordfjord** [comment]
@esjewett I have no contributions to crossfilter, only a passing familiarity with the inner workings.

**Comment by sciyoshi** [comment]
Thanks @esjewett! You can add me as `Samuel Cormier-Iijima <sciyoshi@gmail.com>`

**Comment by esjewett** [comment]
@sciyoshi Done - thanks for you contribution!
