### ISSUE TITLE
expand dimension.top() and dimension.bottom() to include offset parameter

### ISSUE THREAD

**Issue by nreese** [crossfilter/crossfilter#33]
I am looking for a simple way to access the middle of a crossfilter dimension. Example usage is pagination on crossfilter dimension.

I can do this by using the existing API of top() or bottom() and then just grabbing the piece that I need but this seems inefficient to get all of the data to then just use a tiny piece.

Would it be possible to extend the top() and bottom() API to include an optional offset parameter?
For example
dimension.top(10) would return the top 10 records
dimension.top(10, 25) would return the top 10 records starting at index 24 (zero based index).

**Comment by esjewett** [comment]
Sounds reasonable. Others agree?

Technically, it should be a pretty simple change to the top/bottom functions in the dimension. If you'd like to try a pull request with test cases and this change, that would be excellent.

**Comment by tannerlinsley** [comment]
Sounds very good. I say go for it. Write the new tests and submit a PR.
Spectacular idea

**Comment by nreese** [comment]
is there a wiki describing the build process and contributing guidelines?

**Comment by esjewett** [comment]
@nreese Not yet. Here's the process though: Fork the repo, clone your repository locally, `npm install`, `make test` (should all pass), make your changes to files in the src/ and test/ directories, squash commits if that makes sense, and send a pull request.

**Comment by esjewett** [comment]
Oh, right, and run the tests after your changes. :-)

**Comment by nreese** [comment]
Thanks  - that worked.

Where are the API documents generated from?

**Comment by esjewett** [comment]
@nreese API docs are all in the wiki. You can edit it (I think?) or we can update it after the pull request.

**Comment by nreese** [comment]
Does it make sense to update the bottom() method in a similar fashion? For
symmetry it sounds like a good idea but I am not sure of the usefulness

**Comment by esjewett** [comment]
@nreese Yes, please do. If people are paginating, they are probably doing a sorted, often tabular display. Often in this scenario the table sort can be user-defined to sort up or down.

**Comment by esjewett** [comment]
I think this was closed by the reference pull request being merged. So I'm closing :-)
