### ISSUE TITLE
API for groups to have knowledge of add/remove vs. filter operations

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#4]
See below for more detailed approach. Needs to be done for

 - [x] group()  (in pull request #20)
 - [x] groupAll()
 - [x] crossfilter.groupAll()

**Comment by esjewett** [comment]
This is now coming up as a requirement on [Palladio](https://github.com/humanitiesplusdesign/palladio/issues/57). I'd also like to actually move Palladio away from our custom build of Crossfilter and over to this fork. This is the last issue blocking that move. Specifically, we want to be able to calculate unfiltered aggregations on Crossfilter groups to allow comparison of the value of the group under the current filter with the value of the group under no filters. This might sound simple, and it is if you can be sure that things happen in this order: Data loads, groups created, filters applied.

But this is often not the case. Data can be added or removed after groups are created. Groups can be created after filters are already in place. The following needs to be taken into account:

 1. Groups must "see" all records in the Crossfilter at least once, even if a filter is already in place when the group is created.
 2. Groups need to be able to differentiate between records being added/removed because of a filter operation vs. records being added/removed via crossfilter.add and crossfilter.remove.

I'm going to suggest the following non-breaking API changes to Crossfilter (though note that there is a performance impact on group creation if filters are in place, and on data removal):

 1. When creating a group, add all records, then remove records based on filters in place. See [this branch](https://github.com/humanitiesplusdesign/crossfilter/commits/When-initially-building-groups%2C-reduceAdd-all-values) of our fork for the basic idea.
 2. Add a parameter to the add/remove functions in the `group.reduce(add, remove, initial)` API so that they take `p`, `v`, and `n` as parameters. The `n` is a boolean indicating if this record is being permanently added or removed from the Crossfilter (`true` if the result of add/remove operations on the Crossfilter, `false` or `undefined` if this is only due to a filter operation). Groups can use this indicator to decide how to treat a given record. Specifically, if `n === true`, then the group can update its 'unfiltered' aggregations appropriately.
 3. `crossfilter.add` and `crossfilter(data)` will add new records to groups with `add(group, data, true)`.
 4. `crossfilter.remove` will remove records from groups with `remove(group, data, true)`.
 5. (future consideration) `crossfilter.remove` will first add all records (a) being removed that are (b) not currently included in groups (i.e. are filtered out) back into the group using `add(group, data, false)` before removing them using `remove(group, data, true)`. Note that this is currently irrelevant until #6 is resolved as currently all removed records are in the current filter by definition.

I'll create a branch and pull request, but wanted this here for consideration and discussion.

**Comment by tannerlinsley** [comment]
I think that'd be great. We could use those features as well up the road a
bit.

**Comment by esjewett** [comment]
Ok, this is ready to go in pull request #20. It introduces this functionality for dimension.group, dimension.groupAll, and crossfilter.groupAll, along with tests for all of this functionality. `make benchmark` seems to show no performance change for filtering operations, which is what I expected. There will be a small performance impact if there are filters in place when building groups, on crossfilter.add, and for anything that causes a group reset (which I think should't be much of anything).

I will update documentation and then merge, probably on Thursday/Friday unless I hear otherwise. Will be traveling until then, so may not be very available for discussion.

**Comment by esjewett** [comment]
Documentation update is the last paragraph of this section: https://github.com/crossfilter/crossfilter/wiki/API-Reference#group_reduce
