### ISSUE TITLE
drill through

### ISSUE THREAD

**Issue by ksknysn** [crossfilter/crossfilter#40]
Hi,
I have a dataset about tickets like (total tickets):

Depatment |     Group |     Topic  |           SubTopic
-------- |  ------- | ------------ | ----------
Sales,50     |               System,20 |  Web,8  |           Design,6
 IT ,35    |              Software,15 |  Outsource,7    |          Control,8
  |             Workers,10   |  Report,7 |  Overtime,8
  | | Net,20 | Bugs,5
  | |  | IP,3

I show total tickets, max tickets for a day, avg etc. values by filtering months and years. I draw bars over texts above. But i couldn't find any solution, so i decided to get 4 different dataset. And i achieved that. 
But now i need a filtering which affects all datasets. For example when i click software the other datasets filter data related with "software":

Depatment |     Group |     Topic  |           SubTopic
-------- |  ------- | ------------ | ----------
Sales,50     |               System,20 |  **Web,8** |           **Design,6**
 **IT,35** |              **Software,15** |  Outsource,7    |          Control,8
  |             Workers,10   |  **Report,7** |  Overtime,8
  | | Net,20 | **Bugs,5**
  | |  | IP,3

what should i do? i think i can't do these with just one dataset. But  i think how can i do this for two days.
thanks...

**Comment by ksknysn** [comment]
![image](https://cloud.githubusercontent.com/assets/16814924/14349916/e53dc898-fcce-11e5-8316-dc739a792261.png)
this is my real report...

**Comment by esjewett** [comment]
This is a better question for [Stackoverflow](http://stackoverflow.com/questions/tagged/crossfilter) or the [mailing list](https://groups.google.com/forum/#!forum/crossfilter). Will close this issue.

I would say you can certainly do this with Crossfilter if I'm understanding the question. You should look at examples and tutorials (Google "Crossfilter tutorial") that will all explain the first steps in how to do this.

**Comment by derekperkins** [comment]
You might also check out github.com/crossfilter/universe
