### ISSUE TITLE
register crossfilter2 with cdnjs

### ISSUE THREAD

**Issue by gordonwoodhull** [crossfilter/crossfilter#42]
was just about to add dependencies to someone's fiddle and noticed we aren't published. i'm not in the right mode to do this right now (i remember some unavoidable huge checkouts, even though you don't have to save all 12GB on disk) but i can take this on later if no one else wants to.

**Comment by tannerlinsley** [comment]
@etimberg, didn't you just deal with this on github.com/nnnick/Chart.js?

**Comment by esjewett** [comment]
I usually use Rawgit for fiddles. Will that work for the moment?

**Comment by etimberg** [comment]
@tannerlinsley I did. They still haven't accepted my PR, nor commented on it. :frowning:

**Comment by tannerlinsley** [comment]
@cdnjs :(

**Comment by gordonwoodhull** [comment]
I am going ahead with a PR on cdnjs. In the meantime, there is also unpkg:

https://unpkg.com/crossfilter2@latest/crossfilter.js
https://unpkg.com/crossfilter2@latest/crossfilter.min.js

**Comment by gordonwoodhull** [comment]
Wow, that was fun. They have a *lot* of requirements, hopefully I've satisfied enough for them to help me with whatever I missed.

https://github.com/cdnjs/cdnjs/pull/10050

**Comment by gordonwoodhull** [comment]
https://cdnjs.com/libraries/crossfilter2

**Comment by esjewett** [comment]
@gordonwoodhull Thanks so much for doing this.
