### ISSUE TITLE
global variable leak

### ISSUE THREAD

**Issue by MarkHerhold** [crossfilter/crossfilter#47]
I'm turning my inline commit comment into an issue for visibility.

Global variable leak introduced in:
https://github.com/crossfilter/crossfilter/commit/a9d05f03395a955015dbb7fd10094b9911e24939#diff-6dcf89a9f393ad27fc6f8896a6e987ae

See comment here: https://github.com/crossfilter/crossfilter/commit/a9d05f03395a955015dbb7fd10094b9911e24939#commitcomment-17125329

**Comment by esjewett** [comment]
I'm not sure I follow - it looks like that is in a closure. How does it make a global variable available? Or does this mean something else? Thanks!

**Comment by MarkHerhold** [comment]
It doesn't matter that it is in a closure when `'use strict'` is not present. Excluding the use of `var` without `'use strict'` automatically makes the variable global. I only found this issue because it was global in the chrome debugger, so I am pretty sure I am correct about these leaking.

Here's an example program demonstrating the same behavior:

```js
try {
    console.log('attempt 1:' + foo);
} catch (e) {
    console.error('logging foo as a global var failed');
}

function logFoo() {
    foo = 'this is foo';
    console.log('logFoo() called: ' + foo);
}

logFoo();

try {
    console.log('attempt 2: ' + foo);
} catch (e) {
    console.error('logging foo as a global var failed (again)');
}
```

Output:
```
logging foo as a global var failed
logFoo() called: this is foo
attempt 2: this is foo
```

Adding `'use strict'`produces this "compile time" error preventing this nastiness in the first place...
```
    foo = 'this is foo';
        ^

ReferenceError: foo is not defined
    at logFoo (test.js:10:9)
    at Object.<anonymous> (test.js:14:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by MarkHerhold** [comment]
@esjewett note that I re-added `var` in PR #48 so we may not need to take any action if #48 is completed soon.

https://github.com/crossfilter/crossfilter/pull/48/files#diff-6dcf89a9f393ad27fc6f8896a6e987aeR272

**Comment by gordonwoodhull** [comment]
Oh. Originally I thought you were referring to `old_n0` a few lines down, which is also a problem, but this one is bigger.

**Comment by esjewett** [comment]
You're right. I was looking at the wrong side of the diff :-/ I think we'll be able to get #48 merged pretty quickly.

**Comment by esjewett** [comment]
#48 was merged, so I'm marking this as closed.
