### ISSUE TITLE
Unused Variables

### ISSUE THREAD

**Issue by MarkHerhold** [crossfilter/crossfilter#53]
I found these warnings coming from webpack when minifying crossfilter. This issue is a reminder for me or someone else to take a look.

```
Dropping unused variable oldValues [./~/crossfilter2/src/crossfilter.js:138,0]
Dropping unused variable oldIndex [./~/crossfilter2/src/crossfilter.js:139,0]
Dropping unused variable oldIterablesIndexFilterStatus [./~/crossfilter2/src/crossfilter.js:146,0]
```

I am thinking of adding eslint to catch stuff like this.

**Comment by MarkHerhold** [comment]
I've started looking into this and there are a LOT of scoping issues. e.g. `var i` is redefined frequently.

**Comment by gordonwoodhull** [comment]
Although I'm sympathetic with code cleanup, I want to point out that such efforts add noise to the commit history, making it difficult to interpret previous changes. (E.g. it can make it very difficult to use `git blame` to determine where a line of code came from.)

Not an objection, just a request for moderation with such changes. (For example I might object to application of style guidelines.) Thanks for looking into this!

**Comment by MarkHerhold** [comment]
>  I want to point out that such efforts add noise to the commit history, making it difficult to interpret previous changes

In order to create a maintainable project, some sacrifices to the commit history must be made. I don't think anyone wants a clean commit history if it means the code is unreasonably difficult to maintain.

That being said, I'm not changing indentation if I don't have to, only variable declarations.

**Comment by gordonwoodhull** [comment]
Like I said, not objecting, just asking for caution. Thank you!

**Comment by gordonwoodhull** [comment]
Thinking about this further, I probably just need more powerful git tools. It's mostly Github that makes it difficult to view history past one commit. Thanks @MarkHerhold!

**Comment by esjewett** [comment]
@gordonwoodhull Thanks for the thought. I personally don't mind messy Git histories, but I'm sympathetic to those who aren't of the same mind. I probably just haven't run into the same sort of problems.

**Comment by gordonwoodhull** [comment]
It happens to me because whenever there's a line of code I don't understand, I go straight to history to find out where it came from and what lines came with it.
