### ISSUE TITLE
Add bower file to 1.3.X

### ISSUE THREAD

**Issue by mtraynham** [crossfilter/crossfilter#59]
@esjewett can comment, but see https://github.com/dc-js/dc.js/issues/1149

I was going to create a PR, but it seems you cannot do this if there is no branch to target that represents the 1.3.X releases.  So, [here is my branch](https://github.com/mtraynham/crossfilter-1/tree/1.3.13_bower) that I created off the 1.3.13 tag.  We can go down the PR route, but you'll have to branch off the 1.3.13 tag, update to 1.3.14, apply the bower fix and release.

**Comment by gordonwoodhull** [comment]
I went ahead and created a 1.3 branch in case there are further fixes to this line, bumped the version and artifacts, and published to npm as 1.3.14. Thanks @mtraynham!

**Comment by esjewett** [comment]
I think for bower we need a tag as well, don't we? And sorry I never go to this :( Dropped the ball on it.

**Comment by MarkHerhold** [comment]
`bower version patch/minor/major` tags the git repo for you (same as `npm version patch/minor/major`).

http://bower.io/docs/api/#version

**Comment by gordonwoodhull** [comment]
Whoops, yes, done (the git way - the package.json was already updated). I had hesitated because I wasn't sure if you were intentionally avoiding branches, @esjewett. But then I remembered that git branches are lightweight and can always be ignored.

**Comment by esjewett** [comment]
Huh, cool. 👍

**Comment by esjewett** [comment]
@gordonwoodhull Thanks! No, I wasn't avoiding branches. Locally I was branching based on the old tag and then just pushing a new tag instead of a branch, but I think the approach of maintaining a 1.3 branch that we cut releases from is a good one.
