### ISSUE TITLE
crossfilter.remove() to take a test function argument

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#6]
Copy of https://github.com/square/crossfilter/issues/109.

Commit to be made into a pull request: https://github.com/esjewett/crossfilter/commit/09d5ac158f0fc1bb6498fb26d73b0ca0cccbd36b

If anyone sees issues with this, please let me know here. We can also discuss on the PR once that happens.

**Comment by tehsenaus** [comment]
What's the status of this - is your fork stable? What do you need help with?

**Comment by esjewett** [comment]
Hi,

The development in my fork was never quite correct and has now fallen quite a bit behind the current 1.4.0 alpha releases. If you want to work on it, that would be fantastic. It would probably make the most sense to just start a clean fork from the master branch and reference my fork for ideas, keeping in mind that something was flawed about the approach. Unfortunately I have not had time to dive back into it and it doesn't look like I will for at least another couple of weeks.

Thanks,
Ethan

**Comment by tehsenaus** [comment]
Hi Ethan,

I've finally had a chance to work on this, and I've raised a PR here:
https://github.com/crossfilter/crossfilter/pull/81

Would appreciate your feedback!

**Comment by esjewett** [comment]
Fixed in #81.
