### ISSUE TITLE
Enabling 'or' filter

### ISSUE THREAD

**Issue by siims** [crossfilter/crossfilter#60]
Hey,

I happened to read [square/crossfilter pull request](https://github.com/square/crossfilter/pull/22), which introduced possibility to apply multiple filters at once. I couldn't find anything related to that from this code base, so I am wondering a) did I miss something when I was going through crossfilter/crossfilter library? b) or what is the reason for not including such seemingly useful feature?

Good to see that such useful library is getting active attention :+1: 

Best

**Comment by gordonwoodhull** [comment]
Hi @siims, it would be a great feature to have. However I don't understand the code or the description of it. 

It seems like there would have to be another level of iteration somewhere to work with the extra values and ranges, and I don't see it.

It's been quite a few years, but I wonder if @zackham could comment.

**Comment by esjewett** [comment]
Sounds to me like it's a good feature and would allow for applying filters with "or" semantics in a more efficient way than with filterFunction. The pull request would need to be rebased against the current master code base and pretty significantly updated as the internals are undergoing some rework.

**Comment by siims** [comment]
Thank you for information. I would love to see this feature in crossfilter, but as time has no mercy I will use filterFunction for 'or' semantics and keep an eye on crossfilter development. Keep up the good work. Best

**Comment by zackham** [comment]
@esjewett you mention that the internals are undergoing some rework – would it be welcome for me to take a shot at reimplementing this functionality on current master? Or would it make sense to wait until the internals stabilize?  I'm still using the code from that old PR in production and haven't updated crossfilter, but would be happy to take a shot at it if there was interest.

**Comment by esjewett** [comment]
@zackham Absolutely! The internal rework is going to be ongoing, and very slow, so just go for it and we'll see if we can get your work finally merged upstream here :-)

**Comment by gordonwoodhull** [comment]
Oh. I think I see how this works now. When this was implemented there was no possibility to add or remove records from the crossfilter, so there was no need to store the current filter. So it iterates over the passed ranges immediately and values and filters them, and then it's okay that it forgets the ranges/values.

I think to implement something like this now, with the existence of `crossfilter.add` and `crossfilter.remove`, it would have to fall back on a filterFunction for those updates. Which might not be that bad. Or perhaps there is something more clever that I'm missing.

**Comment by esjewett** [comment]
I think it could implement a new filter type (like filterFunction or filterExact) that takes a list of arguments and stores it so that it can be re-applied.
