### ISSUE TITLE
Get all records that satisfy filters

### ISSUE THREAD

**Issue by betalb** [crossfilter/crossfilter#64]
Add global method that will allow to select all records with all filters applied.

Currently this can be achieved by creating dummy dimension, but this has additional memory/speed footprint

**Comment by esjewett** [comment]
Why not use a dummy dimension? I think the memory footprint is going to be incurred either way. No reason to make users pay for it if they don't need it, I would think?

**Comment by tannerlinsley** [comment]
I agree with Ethan. An opt in method would incur the same if not less
optimized performance bottleneck as creating a dimension.

**Comment by betalb** [comment]
Looking at the code, I see that this is possible with just O(N), by iterating over data and checking filters array

Creating dimension will require
* Iterate over data array to execute dimension function
* create index array
* sort it

Other drawback is existing 32 dimensions limitation (I'm talking about 1.3) and If I already have 32 dimensions, this may cause an issue. I understand, that I can take any of existing dimension to achieve similar behavior, just ordering may be different.

New method can use original data ordering, dummy/existing dimension will potentially return data in different order.

**Comment by esjewett** [comment]
If we can do it with no impact on people who don't use it, I'd be open to a `crossfilter.allFiltered` method to go with the existing `crossfilter.all` method in 1.4. Want to send a pull request?

P.S. The internal ordering of data in Crossfilter should not be relied on, so the order of arrays returned by `crossfilter.all` and `group.all` is not guaranteed.

**Comment by betalb** [comment]
Created pull request

**Comment by esjewett** [comment]
Sorry, I saw it and forgot to come back to it. One small comment. Otherwise looks fine to me.
