### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by guilhermecgs** [crossfilter/crossfilter#77]
Sorry for the newbie question, but just to be sure, is [this PR](https://github.com/square/crossfilter/pull/75) (from the original repo) already merged in v1.4?

The main point is: can I use more than 32 dimension in v1.4?

**Comment by gordonwoodhull** [comment]
Yes - see #10

**Comment by guilhermecgs** [comment]
[closing...](https://github.com/crossfilter/crossfilter/releases/tag/1.4.0)

> Support for more than 32 dimensions. Define as many dimensions as you want. Performance is reduced after 8, 16, and 32 dimensions. Special thanks to @sciyoshi.
