### ISSUE TITLE
Incorrect minified version (1.4.0 vs 1.4.1)

### ISSUE THREAD

**Issue by Frozenlock** [crossfilter/crossfilter#82]
While the last commit message and the package.json indicate version 1.4.1, the declared version in the minified file is 1.4.0.

**Comment by esjewett** [comment]
Thanks for filing the issue. That is very odd. I'm going to try to release a 1.4.3 version and hopefully it picks up the version change.

**Comment by Frozenlock** [comment]
Yup, this time it worked.
