### ISSUE TITLE
Filtering issue

### ISSUE THREAD

**Issue by ravirane1985** [crossfilter/crossfilter#85]
Hi,

   I have this weird issue -
in below code I see filtered data even before adding any filter. Both Console Top(Infinity) line produces same result. If I understand correctly, filtered data should appear only after adding filter.
This work if I add debugger while adding filter.

    var facts = crossfilter(data);
    let dim1 = facts.dimension(function(d){ return d.col1; });
    let dim2 = facts.dimension(function(d){ return d.col2; });
    console.log('Before Filter')
    console.log(dim2.group().top(Infinity))
    console.log('Adding Filter')
    dim1.filter('Disa')
    console.log('After Filter')
    console.log(dim2.group().top(Infinity))

**Comment by esjewett** [comment]
The individual groups reference internal data structures in Crossfilter and are updated when the new filter is applied, so they will change when displayed on the console. If you want to see them as they were at the time of the console statement, use `console.log(JSON.stringify(dim2.group().top(Infinity)))`.
