### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#9]
Might make sense to decide on a new name for both the organization and the project (motivated in part by discussion in https://github.com/square/crossfilter/issues/151)

Advantages of a new name:

 1. Reduced confusion regarding which project is which
 2. NPM/Bower registration
 3. Not jerky :-)

Disadvantages of a new name:

 1. Discoverability for existing Crossfilter users will be reduced significantly
 2. Have to go through and rebrand everything, possibly ask projects that depend on Crossfilter to add this project as an optional dependency and mention in their documentation 

One obvious possible new name would be Crossfilter2. Many of the advantages and fewer of the disadvantages.

**Comment by tannerlinsley** [comment]
Crossfilter2 is cool.  It definitely would minimize the disadvantages, and I think it gives the appropriate amount of consideration to square without hijacking their brand.

**Comment by gordonwoodhull** [comment]
Crossfilter2 sounds good to me. They brought it deep into 1.*, let's take it to 2.0!

**Comment by gsklee** [comment]
+1

**Comment by derekperkins** [comment]
I'd rather leave the name the same. https://github.com/infochimps-labs/cube didn't rename anything. I don't think we're planning on any breaking changes or anything that would necessitate a version bump to 2.0, but that's what it sound like. We're mostly looking at building an ecosystem around the existing crossfilter functionality, so leaving the name the same will be the best for discoverability. I think if we're respectful about giving credit to Square while making it obvious it isn't supported by them, we'll be just fine.

**Comment by gordonwoodhull** [comment]
It is probably only necessary if development continues on the original, which is unknown. 

True, the only breaking change I've heard about is the multiple filter set mentioned by @jasondavies here: https://github.com/square/crossfilter/issues/109. Sounds like @esjewett's proposal for a delete filter function was not a breaking change.

**Comment by derekperkins** [comment]
It seems pretty clear to me that there is no development forthcoming on the original repo. RandomEtc said that he would be willing to link to this repo once we've made enough progress. I understand the hesitation by Square to bless us with the crossfilter branding at this nascent stage, but assuming we provide what we are planning, we should quickly be able to migrate the bulk of crossfilter users to this org and live up to the crossfilter name.

**Comment by esjewett** [comment]
I generally agree that a name-change is not necessary just because it's a fork. My only real concern is how we are going to manage npm/bower registration that isn't super-confusing without changing the name. Thoughts?

I also agree on not needing to rename due to breaking changes, as we don't have any on the table. My delete proposal, the 32+ dimensions proposal, and even the web workers proposal (if it's feasible) would be non-breaking. Even the filter sets could be implemented in a non-breaking way (basically the same API as dc.js uses to handle chart groups, was my thought) if we decide to pursue them.

**Comment by derekperkins** [comment]
npm/bower is tougher.
- cf
- cfilter
- crossfilter2
- crossfire :)
![image](https://cloud.githubusercontent.com/assets/3588778/8198752/576f1278-1468-11e5-892c-d6c20c01b9cb.png)

**Comment by gordonwoodhull** [comment]
I think it's pretty common for the npm / bower package name to be different from the repo name, especially with a suffix.

**Comment by esjewett** [comment]
Ok, then I'd be ok leaving the name as is for the moment. On vacation for the next week here but planning to look at npm/bower registration and my enhancement issues when I get back.






On Tue, Jun 16, 2015 at 8:13 PM -0700, "Gordon Woodhull" <notifications@github.com> wrote:












I think it's pretty common for the npm / bower package name to be different from the repo name, especially with a suffix.

**Comment by tannerlinsley** [comment]
We should get this thing registered on npm/bower.  I would vote a `crossfilter2` suffixed name here.  Sure, I wish we had the original, but it sounds like that's not going to happen any time soon.

**Comment by esjewett** [comment]
Agreed.

**Comment by tannerlinsley** [comment]
I just released `1.3.12`.  Not anything monumental, but yes, it did merit it's own release.
