### ISSUE TITLE
Weird sorting issue

### ISSUE THREAD

**Issue by ravirane1985** [crossfilter/crossfilter#91]
I have a column with three values start with space, Tab and Enter -

Javascript natural sorting -

["	tab", "↵newLine", " space"].sort();

["	abc", " abc", "↵newLine"]

But when I group this column -

group.all()

(3) [{…}, {…}, {…}]
0
:
{key: "	tab", value: 1}
1
:
{key: "↵newLine", value: 1}
2
:
{key: " space", value: 1}

Any idea why the natural sort desc key order is not preserved here?

**Comment by esjewett** [comment]
I don't think `group.all` provides a defined sort order. `group.top` will sort by value, not by key. I'm not sure, but I think the internal ordering of groups is a derivative of the behavior of the `crossfilter.bisect` function, which may have different behavior than native Javascript sorting.

**Comment by esjewett** [comment]
Gah - I need to read our own documentation. It's supposed to be in ascending natural order by key. https://github.com/crossfilter/crossfilter/wiki/API-Reference#group_all

So yes, this does appear to be wrong. Do you have a simple working example or would you like to submit a pull request with a failing unit test? Thank you!

**Comment by ravirane1985** [comment]
Hey Ethan, I did some more research today. Conclusion is current crossfilter2 behavior is correct.

Why I was facing this issue -

dimGrp.all()[1].key.toString().charCodeAt(0)
10
"↵newLine".charCodeAt(0)
8629
dimGrp.all()[1].key.toString()
"
newLine"
dimGrp.all()[1].key
"
newLine"
["	tab", "↵newLine", " space"].sort()
(3) ["	tab", " space", "↵newLine"]
[dimGrp.all()[0].key.toString(),dimGrp.all()[1].key.toString(),dimGrp.all()[2].key.toString()].sort()
(3) ["	tab", "↵newLine", " space"]
 

Thanks. I will close this now.
