### ISSUE TITLE
Proposal: Expose applied filters through getters

### ISSUE THREAD

**Issue by thomasgillet** [crossfilter/crossfilter#92]
I'd like to retrieve the filter(s) currently applied to a crossfilter instance (this is the first part of proposal #44).

`dimension.currentFilter()`
Returns the current filter or `null` (i.e the argument given to the latest call to `filter*`).

~~`crossfilter.dimensions()`
Returns an array of all existing dimensions created on this crossfilter instance.
NB: with dimensions having a filter getter, I don't see the need for a _dimension -> filter_ map.~~

**Comment by thomasgillet** [comment]
Ok, I may have been too fast here. Two things where I may need some feedback:

#### Ambiguity: `filter(null)` vs `filterExact(null)`

The  `filter` method sees null as a "no filter" value, while it is a perfectly legitimate value (since it is orderable, as said in the [doc](https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_filterExact)). This is preventing me to make `currentFilter`/`filter` a coherent getter/setter pair. I guess the "no filter" value should have been `undefined` (**not** orderable), but, too late.

So I'm thinking `undefined` as empty value, or a `hasCurrentFilter` method. Or both (since `filterExact(undefined)`, while a very bad thing to do, is still possible).

#### Dimension references in crossfilters

To implement `crossfilter.dimensions` (or even `crossfilter.currentFilters`), I'll need each crossfilter to keep an array of all its dimensions. Simple enough, but are there some other implications I don't see (performance, garbage collection...)?

Then, this may be a topic on its own, since I immediately wonder about `dimension.groups` or even `dimension.parentCrossfilter` and `group.parentDimension`.

**Comment by esjewett** [comment]
Shouldn't be a performance impact from keeping an array of dimensions. You just need to remove the reference from the array when `dimension.dispose` is called so that we don't have a(nother) memory leak.

**Comment by thomasgillet** [comment]
Ok, thanks for the advice.

**Comment by esjewett** [comment]
Can this be closed now that the pull request is merged and deleted?

**Comment by thomasgillet** [comment]
Well, the part about getting the dimensions of a crossfilter is still pending. I planned to make a second pull request for that, but I'm quite late.
But then would it be actually useful to someone? I know getting filters from a dimension is enough for me. What about @MarkHerhold who wrote the proposal in the first place?

**Comment by MarkHerhold** [comment]
I haven't worked on the original project for quite a while, but I believe your implementation included everything that I had needed. I only needed to get the current filters from a dimension I had a reference to, not anything more complicated.

Good job with this 👍

**Comment by thomasgillet** [comment]
Thanks Mark. Then I close the issue, since I'd not have much time to do it anyway.

**Comment by esjewett** [comment]
If you run into another API change that would be helpful, please feel free to open another issue. The ideas and contributions are both really appreciated.

**Comment by thomasgillet** [comment]
Yes I have some more ideas, hope I'll have time to at least open a discussion about some of them...
