### ISSUE TITLE
dimension.filterAll() not working as documented

### ISSUE THREAD

**Issue by JohnnyRando** [crossfilter/crossfilter#96]
When the following code is run, the first console.log is returning the contents of the crossfilter instance, but the second console.log is return empty brackets.

The API reference states that the dimension.filterAll() method “Clears any filters on this dimension, **selecting all records** and returning this dimension” but no records are showing.

var cf = require('./crossfilter.js');

var payments = cf([
  {date: "2011-11-14T16:17:54Z", quantity: 2, total: 190, tip: 100, type: "tab", productIDs:["001"]},
  {date: "2011-11-14T16:20:19Z", quantity: 2, total: 190, tip: 100, type: "tab", productIDs:["001", "005"]},
  {date: "2011-11-14T16:28:54Z", quantity: 1, total: 300, tip: 200, type: "visa", productIDs:["004" ,"005"]}
]);
var paymentsByTotal = payments.dimension(function(d) { return d.total; });

console.log(JSON.stringify(payments.all()))
console.log(JSON.stringify(paymentsByTotal.filterAll()))

**Comment by esjewett** [comment]
Does it not return the dimension? It does select all records, but it doesn't return them. You have to query the dimension/groups to get the records. Perhaps it should just read “Clears any filters on this dimension, returning this dimension”. I'll leave this open for now as a reminder to revisit this eventually.

**Comment by gordonwoodhull** [comment]
I've seen this confusion a lot recently, so [I added a Gotcha to the documentation](https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#dimension-filters-dont-return-the-current-values). It's natural to think that `dimension.filter()` behaves like JavaScript's `array.filter()` but this is not the case.

**Comment by esjewett** [comment]
@gordonwoodhull Of course it's a gotcha! Why didn't I think of that? Thank you!
