### ISSUE TITLE
Access to Dimension Records (Bisector, Iterator)

### ISSUE THREAD

**Issue by thatcort** [crossfilter/crossfilter#99]
It would be extremely helpful to be able to access the sorted records for a dimension *without* making a copy of the array. A bisector and an iterator would be great. Indexed access would also be helpful, even though it can be faked with top(1, offset).

My use case is as follows:
I have a dimension for which I need the count of records with a dimension value greater than a threshold. These records should be affected by filters on other dimensions, but I don't want to add a filter that affects other dimensions.

Apologies if this functionality already exists, but I don't see how to accomplish this in a performant way.

**Comment by thatcort** [comment]
A dimension bisect method would be perfect. I need to know the count of rows in a dimension (with other dimensions' filters applied) that have a dimension value greater than a threshold. With that value I could then access the row data using the dimension top/bottom methods.

The code in the last line of your reply would be quite slow, since it allocates three arrays and does three linear searches (3*O(n) in both time and space). I suppose that I can run the bisector on `cf.allFiltered().sort((a, b) => dim.accessor(b) - dim.accessor(a))`, but this also seems slow. Still O(n) `allFiltered()` + O(n log n) `sort()` + O(log n) `bisect()` is significantly better and I can reuse the array between changes only needing to re-sort and bisect for each dimension.

It doesn't sound like Crossfilter can easily be made to help here. If there's a better approach than what I just described, please let me know. Otherwise, feel free to close the ticket. Thanks for the help.

**Comment by thatcort** [comment]
I can implement something like what you suggest, iterating over `cf.allFiltered()`, but this will be slow as data size or the number of dimensions grows. I'd just use loops to avoid the allocations inherent in map and filter, but the time complexity will still be O(2n).

Another suggestion, then, would be to add additional parameters to the onChange callback. By passing in the added and removed rows I'd be able to maintain these counts while iterating over much shorter arrays. Would that be a possible addition to the library?

**Comment by esjewett** [comment]
Hmmm. It occurs to me that you could do the equivalent of your alternative suggestion by creating a custom reducer on `dimension.groupAll`. Could you play with that API and see what you think? You could also use Reductio's `filter` and `valueList` methods, which would do the same thing - https://github.com/crossfilter/reductio

**Comment by thatcort** [comment]
Thanks, I'll take a look.

I'm trying to convert an existing app to use Crossfilter so that I can combine it's custom visualizations with some standard dc.js ones and take advantage of Crossfilter's incremental approach to filtering for performance gains. I'm running into issues where things in the custom data model seem difficult in Crossfilter.

The next issue I've realized is that there are cases where I want to group a dimension's results with only its own filter applied. In one of my visualizations I have a threshold filtering that operates as a first step. Then there are a number of other visualizations that allow selections within the thresholded results, and show both the before and after (intersected selections) overlaid. With crossfilter it seems like there is no way to ask for the results with only the threshold applied and not all the other dimension filters.

It may be that what I'm doing isn't a good use case for Crossfilter, but it seems so close!

Finally, as an aside, it would be great if there was a doc on the wiki describing the internal design of Crossfilter. This would help with contributing to the project.

**Comment by esjewett** [comment]
Cool - I'd suggest you put together working examples showing what you are looking in these cases. It makes it a lot quicker to evaluate. Overall, StackOverflow is a better place for these types of questions than Github issues - just tag it "crossfilter" and someone will see it. If it turns out there is a bug or a new feature required, feel free to open an issue though.

We would like to have multiple filter sets and allow intersections and unions of them, but that is not there now. But there may be a way to do this given some more details about what you are trying to achieve.

Going to close this for now.
